// <auto-generated />
namespace Exam1.Migrations.AttendMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Relationshipchanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relationshipchanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201901081731133_Relationship changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
