// <auto-generated />
namespace Exam1.Migrations.ApplicationDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RoleIDadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoleIDadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201901081841482_RoleID added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
